### ISSUE TITLE
audio balance broke silent video

### ISSUE THREAD

**Issue by benyaminl** [robertosartori/Audio-Balance#2]
on instargam, facebook, and other which is the video default is played, but with no sound, nah audio balance break it, so the video sound appear even I don't change it, or even I want to mute it, it won't work.

**Comment by roberto-sartori-gl** [comment]
Could you post Xposed log?

**Comment by benyaminl** [comment]
[xposed_error_20160514_143743.txt](https://github.com/robertosartori/Audio-Balance/files/264415/xposed_error_20160514_143743.txt)

Okay, try this maybe?

Benyamin Limanto

sent from my Asus fonepad

**Comment by roberto-sartori-gl** [comment]
Have you tried without the module? I mean, disable it, reboot and try for example a Facebook video (mute it). I've never had you problem, so i can't reproduce...

**Comment by benyaminl** [comment]
Yes, when I deleted or disable, the problem solved. Just it. But I need
your software because, my headset is not stable between left and right

Benyamin Limanto

sent from my Asus fonepad

**Comment by roberto-sartori-gl** [comment]
Ok. So do that. Enable the module, reboot, start a facebook video (and mute it) and then give me a new Xposed log.

**Comment by benyaminl** [comment]
[xposed_error_20160514_160528.txt](https://github.com/robertosartori/Audio-Balance/files/264441/xposed_error_20160514_160528.txt)
Okay, maybe this, but Also on instagram, so I tried open instagram

Benyamin Limanto

sent from my Asus fonepad
On May 14, 2016 3:59 PM, "Roberto Sartori" notifications@github.com wrote:

> Ok. So do that. Enable the module, reboot, start a facebook video (and
> mute it) and then give me a new Xposed log.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/robertosartori/Audio-Balance/issues/2#issuecomment-219209221

---

May 14, 2016 2:03:27 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KVT49L.WW_K016-V4.4.0-20150407' with fingerprint 'asus/WW_K016/K016_1:4.4.2/KVT49L/WW_K016-V4.4.0-20150407:user/release-keys'
Loading modules from /data/app/com.robertogl.audiobalance-1.apk
  Loading class com.robertogl.audiobalance.MainNew
Loading modules from /data/app/de.defim.apk.notifyclean-1.apk
  Loading class de.defim.apk.notifyclean.Xposed
    [NotifyClean] initialized
  Loading class de.defim.apk.notifyclean.Xreszs
  Loading class de.defim.apk.notifyclean.Xcheck
Loading modules from /mnt/asec/com.ihelp101.instagram-1/pkg.apk
  File does not exist
Loading modules from /data/app/de.defim.apk.bootmanager-1.apk
  Loading class de.defim.apk.bootmanager.Xposed
    [BootManager] initialized
  Loading class de.defim.apk.bootmanager.Xcheck
Loading modules from /data/app/ma.wanam.youtubeadaway-2.apk
  Loading class ma.wanam.youtubeadaway.Xposed
Loading modules from /data/app/de.blinkt.vpndialogxposed-1.apk
  Loading class de.blinkt.vpndialogxposed.VpnDialogPatcher
Loading modules from /data/app/pl.cinek.adblocker-1.apk
  Loading class pl.cinek.adblocker.Main
java.lang.NullPointerException
    at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
    at pl.cinek.adblocker.Main.handleLoadPackage(Main.java:34)
    at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
    at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
    at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
    at de.robv.android.xposed.XposedBridge$2.beforeHookedMethod(XposedBridge.java:228)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.server.ServerThread.initAndLoop(Native Method)
    at com.android.server.SystemServer.main(SystemServer.java:1400)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.SystemServer.main(Native Method)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
onCreate: com.android.launcher3.Launcher
onCreate: com.android.launcher3.Launcher
onCreate: com.android.launcher3.Launcher
com.asus.UpdateLauncher.UpdateLauncher
android.intent.action.BOOT_COMPLETED
com.asus.UpdateLauncher.UpdateLauncher
android.intent.action.BOOT_COMPLETED
onCreate: com.asus.UpdateLauncher.UpdateLauncher
YouTube AdAway: trying brute force way...
YouTube AdAway: succes hook for sequence: class =ngc param=ldr for YouTube 11.16.62
YouTube AdAway: trying brute force way...
YouTube AdAway: succes hook for sequence: class =ngc param=ldr for YouTube 11.16.62
de.robv.android.xposed.installer.WelcomeActivity
android.intent.action.MAIN
onCreate: de.robv.android.xposed.installer.WelcomeActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: com.robertogl.audiobalance.SettingsActivity
com.arlosoft.macrodroid.MacroDroidActivity
android.intent.action.MAIN
onCreate: com.arlosoft.macrodroid.MacroDroidActivity
com.arlosoft.macrodroid.SelectTriggerActivity
com.arlosoft.macrodroid.SelectTriggerActivity
com.arlosoft.macrodroid.SelectTriggerActivity
onCreate: com.arlosoft.macrodroid.SelectTriggerActivity
com.arlosoft.macrodroid.SelectActionActivity
com.arlosoft.macrodroid.SelectActionActivity
com.arlosoft.macrodroid.SelectActionActivity
onCreate: com.arlosoft.macrodroid.SelectActionActivity
de.robv.android.xposed.installer.WelcomeActivity
android.intent.action.MAIN
onCreate: de.robv.android.xposed.installer.WelcomeActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: de.robv.android.xposed.installer.XposedInstallerActivity
com.arlosoft.macrodroid.SelectActionActivity
onCreate: com.arlosoft.macrodroid.SelectActionActivity
com.arlosoft.macrodroid.SelectConstraintActivity
com.arlosoft.macrodroid.SelectConstraintActivity
com.arlosoft.macrodroid.SelectConstraintActivity
onCreate: com.arlosoft.macrodroid.SelectConstraintActivity
com.arlosoft.macrodroid.MacroDroidActivity
com.arlosoft.macrodroid.MacroDroidActivity
com.arlosoft.macrodroid.MacroDroidActivity
com.arlosoft.macrodroid.MacroListActivity
com.arlosoft.macrodroid.MacroListActivity
com.arlosoft.macrodroid.MacroListActivity
onCreate: com.arlosoft.macrodroid.MacroListActivity
com.arlosoft.macrodroid.EditMacroActivity
com.arlosoft.macrodroid.EditMacroActivity
com.arlosoft.macrodroid.EditMacroActivity
onCreate: com.arlosoft.macrodroid.EditMacroActivity
de.robv.android.xposed.installer.WelcomeActivity
android.intent.action.MAIN
onCreate: de.robv.android.xposed.installer.WelcomeActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.WelcomeActivity
android.intent.action.MAIN
onCreate: de.robv.android.xposed.installer.WelcomeActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: de.robv.android.xposed.installer.XposedInstallerActivity
com.arlosoft.macrodroid.EditMacroActivity
com.arlosoft.macrodroid.MacroListActivity
com.arlosoft.macrodroid.MacroListActivity
com.arlosoft.macrodroid.MacroListActivity
com.arlosoft.macrodroid.EditMacroActivity
com.arlosoft.macrodroid.EditMacroActivity
com.arlosoft.macrodroid.EditMacroActivity
onCreate: com.arlosoft.macrodroid.EditMacroActivity
de.robv.android.xposed.installer.WelcomeActivity
android.intent.action.MAIN
onCreate: de.robv.android.xposed.installer.WelcomeActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: de.robv.android.xposed.installer.XposedInstallerActivity
com.arlosoft.macrodroid.AddActionActivity
com.arlosoft.macrodroid.AddActionActivity
onCreate: com.arlosoft.macrodroid.AddActionActivity
com.deezer.android.ui.activity.LauncherActivity
android.intent.action.MAIN
onCreate: com.deezer.android.ui.activity.LauncherActivity
com.deezer.android.ui.TabBarActivity
com.deezer.android.ui.TabBarActivity
com.deezer.android.ui.TabBarActivity
onCreate: com.deezer.android.ui.TabBarActivity
onCreate: com.android.systemui.recent.RecentsActivity
onCreate: com.android.systemui.recent.RecentsActivity
onCreate: com.robertogl.audiobalance.SettingsActivity
com.whatsapp.Main
android.intent.action.MAIN
onCreate: com.whatsapp.Main
com.whatsapp.HomeActivity
com.whatsapp.HomeActivity
com.whatsapp.HomeActivity
onCreate: com.whatsapp.HomeActivity
com.whatsapp.WebSessionsActivity
com.whatsapp.WebSessionsActivity
onCreate: com.whatsapp.WebSessionsActivity
com.whatsapp.qrcode.QrCodeActivity
com.whatsapp.qrcode.QrCodeActivity
onCreate: com.whatsapp.qrcode.QrCodeActivity
com.opera.mini.android.Browser
https://www.facebook.com/n/?emanuelcaesar96%2Fposts%2F1338817026134761&comment_id=1338827156133748&aref=1463195462956822&medium=push&mid=532c474387444G5ec7634aG532c4bdce7716Gb7Gfed7&app=895302423856079
onCreate: com.opera.mini.android.Browser
com.opera.android.MiniActivity
https://www.facebook.com/n/?emanuelcaesar96%2Fposts%2F1338817026134761&comment_id=1338827156133748&aref=1463195462956822&medium=push&mid=532c474387444G5ec7634aG532c4bdce7716Gb7Gfed7&app=895302423856079
com.opera.android.MiniActivity
https://www.facebook.com/n/?emanuelcaesar96%2Fposts%2F1338817026134761&comment_id=1338827156133748&aref=1463195462956822&medium=push&mid=532c474387444G5ec7634aG532c4bdce7716Gb7Gfed7&app=895302423856079
com.opera.android.MiniActivity
https://www.facebook.com/n/?emanuelcaesar96%2Fposts%2F1338817026134761&comment_id=1338827156133748&aref=1463195462956822&medium=push&mid=532c474387444G5ec7634aG532c4bdce7716Gb7Gfed7&app=895302423856079
onCreate: com.opera.android.MiniActivity
YouTube AdAway: trying brute force way...
YouTube AdAway: succes hook for sequence: class =ngc param=ldr for YouTube 11.16.62
jp.naver.line.android.activity.SplashActivity
android.intent.action.MAIN
onCreate: jp.naver.line.android.activity.SplashActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
onCreate: jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
onCreate: jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.schemeservice.LineSchemeServiceActivity
line://ch/1453907334/0m016ac9b51a6d01307c6d284626746e266c66636823117d46122a693a6c2f3a376a6135603e
jp.naver.line.android.activity.schemeservice.LineSchemeServiceActivity
line://ch/1453907334/0m016ac9b51a6d01307c6d284626746e266c66636823117d46122a693a6c2f3a376a6135603e
jp.naver.line.android.activity.schemeservice.LineSchemeServiceActivity
line://ch/1453907334/0m016ac9b51a6d01307c6d284626746e266c66636823117d46122a693a6c2f3a376a6135603e
onCreate: jp.naver.line.android.activity.schemeservice.LineSchemeServiceActivity
jp.naver.line.android.activity.channel.token.ChannelTokenLoadingActivity
jp.naver.line.android.activity.channel.token.ChannelTokenLoadingActivity
jp.naver.line.android.activity.channel.token.ChannelTokenLoadingActivity
onCreate: jp.naver.line.android.activity.channel.token.ChannelTokenLoadingActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
onCreate: jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: jp.naver.line.android.activity.chathistory.ChatHistoryActivity
de.robv.android.xposed.installer.WelcomeActivity
android.intent.action.MAIN
onCreate: de.robv.android.xposed.installer.WelcomeActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: com.android.internal.app.ChooserActivity
onCreate: com.google.android.gm.ComposeActivityGmail
android.intent.action.CHOOSER
android.intent.action.CHOOSER
android.intent.action.CHOOSER
android.intent.action.CHOOSER
onCreate: com.android.internal.app.ChooserActivity
onCreate: com.android.internal.app.ChooserActivity
com.asus.filemanager.activity.FileManagerGetContent
android.intent.action.GET_CONTENT
com.asus.filemanager.activity.FileManagerGetContent
android.intent.action.GET_CONTENT
com.asus.filemanager.activity.FileManagerGetContent
android.intent.action.GET_CONTENT
com.asus.filemanager.activity.FileManagerGetContent
android.intent.action.GET_CONTENT
com.asus.filemanager.activity.FileManagerGetContent
android.intent.action.GET_CONTENT
com.asus.filemanager.activity.FileManagerGetContent
android.intent.action.GET_CONTENT
onCreate: com.asus.filemanager.activity.FileManagerGetContent
onCreate: com.asus.filemanager.activity.FileManagerGetContent
onCreate: com.google.android.gm.ui.MailActivityGmail
onCreate: com.google.android.gm.ui.MailActivityGmail
jp.naver.line.android.activity.SplashActivity
android.intent.action.MAIN
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
onCreate: jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.schemeservice.LineSchemeServiceActivity
line://ch/1453907334/0m016ad9ea1a6d0130343e7c4e267760236c66636c2541204e422f3c7d282b39323b336432
jp.naver.line.android.activity.schemeservice.LineSchemeServiceActivity
line://ch/1453907334/0m016ad9ea1a6d0130343e7c4e267760236c66636c2541204e422f3c7d282b39323b336432
jp.naver.line.android.activity.schemeservice.LineSchemeServiceActivity
line://ch/1453907334/0m016ad9ea1a6d0130343e7c4e267760236c66636c2541204e422f3c7d282b39323b336432
onCreate: jp.naver.line.android.activity.schemeservice.LineSchemeServiceActivity
jp.naver.line.android.activity.channel.token.ChannelTokenLoadingActivity
jp.naver.line.android.activity.channel.token.ChannelTokenLoadingActivity
jp.naver.line.android.activity.channel.token.ChannelTokenLoadingActivity
onCreate: jp.naver.line.android.activity.channel.token.ChannelTokenLoadingActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.channel.ChannelBrowserActivity
onCreate: jp.naver.line.android.activity.channel.ChannelBrowserActivity
jp.naver.line.android.activity.SplashActivity
android.intent.action.MAIN
onCreate: jp.naver.line.android.activity.SplashActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
onCreate: jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: com.android.systemui.recent.RecentsActivity
onCreate: com.android.systemui.recent.RecentsActivity
com.arlosoft.macrodroid.DummyActivity
onCreate: com.arlosoft.macrodroid.DummyActivity
jp.naver.line.android.activity.SplashActivity
android.intent.action.MAIN
onCreate: jp.naver.line.android.activity.SplashActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
onCreate: jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: com.google.android.gm.ComposeActivityGmail
onCreate: com.google.android.gm.ComposeActivityGmail
onCreate: com.google.android.gm.ui.MailActivityGmail
onCreate: com.google.android.gm.ui.MailActivityGmail
jp.naver.line.android.activity.SplashActivity
android.intent.action.MAIN
onCreate: jp.naver.line.android.activity.SplashActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
onCreate: jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.SplashActivity
android.intent.action.MAIN
onCreate: jp.naver.line.android.activity.SplashActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
onCreate: jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.search.SearchMainActivity
jp.naver.line.android.activity.search.SearchMainActivity
jp.naver.line.android.activity.search.SearchMainActivity
onCreate: jp.naver.line.android.activity.search.SearchMainActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.chathistory.ChatHistoryActivity
onCreate: jp.naver.line.android.activity.chathistory.ChatHistoryActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
jp.naver.line.android.activity.main.MainActivity
com.instagram.android.activity.MainTabActivity
onCreate: com.instagram.android.activity.MainTabActivity
onCreate: com.instagram.android.activity.ActivityInTab
de.robv.android.xposed.installer.WelcomeActivity
android.intent.action.MAIN
onCreate: de.robv.android.xposed.installer.WelcomeActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: de.robv.android.xposed.installer.XposedInstallerActivity
com.arlosoft.macrodroid.action.activities.ConfirmDialogActivity
onCreate: com.arlosoft.macrodroid.action.activities.ConfirmDialogActivity
com.arlosoft.macrodroid.action.activities.ConfirmDialogActivity

## onCreate: com.arlosoft.macrodroid.action.activities.ConfirmDialogActivity

May 14, 2016 9:00:52 AM UTC
Loading Xposed v54 (for Zygote)...
Running ROM 'KVT49L.WW_K016-V4.4.0-20150407' with fingerprint 'asus/WW_K016/K016_1:4.4.2/KVT49L/WW_K016-V4.4.0-20150407:user/release-keys'
Loading modules from /data/app/de.defim.apk.notifyclean-1.apk
  Loading class de.defim.apk.notifyclean.Xposed
    [NotifyClean] initialized
  Loading class de.defim.apk.notifyclean.Xreszs
  Loading class de.defim.apk.notifyclean.Xcheck
Loading modules from /mnt/asec/com.ihelp101.instagram-1/pkg.apk
  File does not exist
Loading modules from /data/app/de.defim.apk.bootmanager-1.apk
  Loading class de.defim.apk.bootmanager.Xposed
    [BootManager] initialized
  Loading class de.defim.apk.bootmanager.Xcheck
Loading modules from /data/app/ma.wanam.youtubeadaway-2.apk
  Loading class ma.wanam.youtubeadaway.Xposed
Loading modules from /data/app/de.blinkt.vpndialogxposed-1.apk
  Loading class de.blinkt.vpndialogxposed.VpnDialogPatcher
Loading modules from /data/app/pl.cinek.adblocker-1.apk
  Loading class pl.cinek.adblocker.Main
java.lang.NullPointerException
    at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
    at pl.cinek.adblocker.Main.handleLoadPackage(Main.java:34)
    at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:20)
    at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:34)
    at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:70)
    at de.robv.android.xposed.XposedBridge$2.beforeHookedMethod(XposedBridge.java:228)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:611)
    at com.android.server.ServerThread.initAndLoop(Native Method)
    at com.android.server.SystemServer.main(SystemServer.java:1400)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
    at com.android.server.SystemServer.main(Native Method)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
onCreate: com.android.launcher3.Launcher
onCreate: com.android.launcher3.Launcher
onCreate: com.android.launcher3.Launcher
com.asus.UpdateLauncher.UpdateLauncher
android.intent.action.BOOT_COMPLETED
com.asus.UpdateLauncher.UpdateLauncher
android.intent.action.BOOT_COMPLETED
onCreate: com.asus.UpdateLauncher.UpdateLauncher
YouTube AdAway: trying brute force way...
YouTube AdAway: succes hook for sequence: class =ngc param=ldr for YouTube 11.16.62
com.instagram.android.activity.MainTabActivity
onCreate: com.instagram.android.activity.MainTabActivity
onCreate: com.instagram.android.activity.ActivityInTab
de.robv.android.xposed.installer.WelcomeActivity
android.intent.action.MAIN
onCreate: de.robv.android.xposed.installer.WelcomeActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
de.robv.android.xposed.installer.XposedInstallerActivity
onCreate: de.robv.android.xposed.installer.XposedInstallerActivity
